[project]
name = "jarvis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "customtkinter>=5.2.2",
    "gtts>=2.5.4",
    "pyaudio>=0.2.14",
    "pygame>=2.6.1",
    "pyttsx3>=2.99",
    "speechrecognition>=3.14.5",
]
